
# helm upgrade --install data-generators ./data-generators
# helm uninstall data-generators

replicaCount: 1

application:
  labelValue: datagenerator

infrastructure:
  namespace: datagenerators
  appName: datagenerator

image:
  name: "izzyacademy/data-generators"
  pullPolicy: IfNotPresent
  tag: "2.0"

resources:
  limits:
     cpu: 1000m
     memory: 4096Mi
  requests:
     cpu: 750m
     memory: 2048Mi

config:
  mysql_host: "mysql-external.mysql56.svc.cluster.local"
  mysql_port: "3306"
  mysql_username: "application"
  mysql_password: "db3k4Cc"
  mysql_database: "ecommerce"
  min_order_interval_seconds: "1"
  max_order_interval_seconds: "5"
  shipment_interval_seconds: "5" # used for both shipments and deliveries
  shipment_count: "10" # used for both shipments and deliveries
  order_return_interval_seconds: "2"
  order_return_age_seconds: "60"
  order_return_count: "64"
  replenishment_interval_seconds: "10"